Survey/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    # Standard pages
    url(r'^home/$', views.index, name='home'),
    # User pages
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.CurrentCustomUserDetailView.as_view(), name='profile'),  # Utente corrente
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^profile/edit$', views.UpdateProfileView.as_view(), name='edit_profile'),  # Utente corrente
    # Survey pages
    url(r'^survey/$', views.survey, name='survey'),
    url(r'^survey_questions/$' , views.survey_questions, name='survey_questions'),
    url(r'^question/(?P<survey_id>[0-9]+)/(?P<topic_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.question, name='question'),
    url(r'^vote/(?P<question_id>[0-9]+)/$', views.vote, name='vote'),
    url(r'^report/(?P<survey_id>[0-9]+)/$', views.report, name='report'),
    url(r'^skip/(?P<survey_id>[0-9]+)/$', views.skip, name='skip'),
    # Development
    url(r'^users/$', views.CustomUserListView.as_view(), name='users'),                                                 # Utenti
    # url(r'^user/(?P<id_card>\d+)$', views.CustomUserDetailView.as_view(), name='user_detail'),                        # Utente
]

SurveyProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Survey import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url('^', include('django.contrib.auth.urls')),
    url('', include('Survey.urls')),
]

Survey/models.py
from datetime import datetime, timedelta
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from .validators import validate_file_extension

#####


class CustomUserManager(BaseUserManager):

    def _create_user(self, id_card, password, **extra_fields):
        """
        Creates and saves a User with the given id card and password.
        """
        if not id_card:
            raise ValueError('Users must have an identity card')
        user = self.model(
            id_card=id_card,
            **extra_fields      #TODO: normalize_id_card
        )
        # user = self.model(id_card=id_card, email=email, TODO aggiungere i campi necessari in fase di creazione
        #                   date_joined=now)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, id_card, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(id_card, password, **extra_fields)

    # def create_staffuser(self, id_card, password):
    #     """
    #     Creates and saves a staff user with the given id card and password.
    #     """
    #     user = self.create_user(
    #         id_card,
    #         password=password,
    #     )
    #     user.is_staff = True
    #     user.save(using=self._db)
    #     return user

    def create_superuser(self, id_card, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(id_card, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):

    # --- Fields ---
    # Primary Key
    id_card = models.CharField(
        verbose_name='identity card',
        max_length=9,
        unique=True,
    )
    # Mandatory for real identification
    id_card_scan = models.FileField(verbose_name="Scansione ID Card", upload_to="documents/", validators=[validate_file_extension], blank=True)
    email = models.EmailField(verbose_name=('email address'), max_length=254, unique=True, blank=True)
    first_name = models.CharField('first name', max_length=30, blank=True)
    last_name = models.CharField('last name', max_length=30, blank=True)
    # Extra Fields
    # avatar = models.ImageField(upload_to="avatars/", null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    comune = models.CharField('comune', max_length=30, blank=True)
    provincia = models.CharField('provincia', max_length=30, blank=True)
    indirizzo = models.CharField('indirizzo', max_length=120, blank=True)
    date_joined = models.DateTimeField('date joined', default=timezone.now)
    # -- Mandatory for implementation
    is_active = models.BooleanField(default=True)
    # Can login in admin panel
    is_staff = models.BooleanField(default=False)

    # Hook
    objects = CustomUserManager()

    # --- STRINGS ---
    # -- Mandatory for implementation
    # - Unique identifier
    USERNAME_FIELD = 'id_card'
    # - Value returned by get_email_field_name()
    EMAIL_FIELD = 'email'
    # - Field prompted when creating user via createsuperuser
    # REQUIRED_FIELDS = ['date_of_birth', ...]

    # --- METHODS ---
    # - Mandatory for implementation
    def get_full_name(self):
        # The user is identified by their email address
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()
        # return self.id_card

    def get_short_name(self):
        # The user is identified by their email address
        return self.first_name

    def get_absolute_url(self):
        #return reverse('user-detail', args=[str(self.id_card)])
        return reverse('profile')

    def __str__(self):              # __unicode__ on Python 2
        return self.id_card

    # def has_perm(self, perm, obj=None):
    #     "Does the user have a specific permission?"
    #     # Simplest possible answer: Yes, always
    #     return True
    #
    # def has_module_perms(self, app_label):
    #     "Does the user have permissions to view the app `app_label`?"
    #     # Simplest possible answer: Yes, always
    #     return True
    #
    # @property
    # def is_staff(self):
    #     "Is the user a member of staff?"
    #     return self.staff
    #
    # @property
    # def is_admin(self):
    #     "Is the user a admin member?"
    #     return self.admin
    #
    # @property
    # def is_active(self):
    #     "Is the user active?"
    #     return self.active


class Survey(models.Model):
    survey_title = models.CharField(max_length=120)
    survey_description = models.CharField(max_length=255)

    class Meta:
        permissions = (("can_vote", "Vote questions in the survey"),
                       ("can_report", "Can see the results of the survey"),)

    def __str__(self):
        return self.survey_title


class Topic(models.Model):
    topic_title = models.CharField(max_length=120)
    topic_description = models.CharField(max_length=255)
    survey_id = models.ForeignKey(Survey, on_delete=models.CASCADE)

    def __str__(self):
        return self.topic_title

class Question(models.Model):

    question_text = models.CharField(max_length=255)
    # Valutare inserimento ChoiceField
    answer_1 = models.CharField(max_length=255)
    answer_2 = models.CharField(max_length=255)
    answer_3 = models.CharField(max_length=255)
    # Voti ottenuti dalle risposte (abbozzato, si cercherà una soluzione migliore in futuro)
    votes_1 = models.IntegerField(default = 0)
    votes_2 = models.IntegerField(default = 0)
    votes_3 = models.IntegerField(default = 0)
    pub_date = models.DateTimeField('date published')
    topic_id = models.ForeignKey(Topic, on_delete=models.CASCADE)

    __original_answers = None

    def __init__(self, *args, **kwargs):
        super(Question, self).__init__(*args, **kwargs)
        self.__original_answers = [self.answer_1,self.answer_2,self.answer_3]

    def __str__(self):
        return self.question_text

    def save(self, *args, **kwargs):
        if (self.answer_1 != self.__original_answers[0] or self.answer_2 != self.__original_answers[1] or self.answer_3 != self.__original_answers[2]):
            self.votes_1 = 0
            self.votes_2 = 0
            self.votes_3 = 0
            Completed.objects.filter(surveyId = self.topic_id.survey_id.id).delete()
            SubscribedSurveyQuestion.objects.filter(questionId = self.pk).delete()

        super(Question, self).save(*args, **kwargs) # Call the "real" save() method.

class Completed(models.Model):
    surveyId = models.ForeignKey(Survey, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

class SubscribedSurveyQuestion(models.Model):
    username = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    surveyId = models.ForeignKey(Survey, on_delete=models.CASCADE)
    questionId = models.ForeignKey(Question, on_delete=models.CASCADE)
    # 0 = false, 1 = true
    completed = models.IntegerField(default=0)
    # Va collegata con le possibili risposte delle relativa Question?
    choice = models.CharField(max_length=255)
    # Chiama datetime.now solo quando aggiunge il record
    # Utility per il futuro:
    # date= models.DateTimeField(default=datetime.now()+timedelta(days=30))
    subscription_date = models.DateTimeField(default=datetime.now, blank=True)

    class Meta:
        unique_together = (("username", "surveyId", "questionId"),)

    def __str__(self):
        return self.choice

Survey/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import UserCreationForm
import os
from django.core.exceptions import ValidationError
from .models import CustomUser
from django.contrib.auth.models import Group
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth import get_user_model

# class RegisterForm(forms.ModelForm):
#     # campi da presentare
#     email = forms.EmailField(max_length=254)
#     password = forms.CharField(widget=forms.PasswordInput)
#     password2 = forms.CharField(label='Conferma password', widget=forms.PasswordInput)
#
#     class Meta:
#         model = CustomUser
#         fields = ('id_card','email', 'password', 'password2')   #campi da salvare
#
#     #TODO eliminare?
#     def clean_id_card(self):
#         id_card = self.cleaned_data.get('id_card')
#         qs = CustomUser.objects.filter(id_card=id_card)
#         if qs.exists():
#             raise forms.ValidationError("id card esistente")
#         return id_card
#
#     def clean_password2(self):
#         # Check that the two password entries match
#         password = self.cleaned_data.get("password")
#         password2 = self.cleaned_data.get("password2")
#         if password and password2 and password != password2:
#             raise forms.ValidationError("Le password non corrispondono!")
#         return password2


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('id_card',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Le password non corrispondono")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUser
        fields = ('id_card', 'password', 'is_active', 'is_superuser')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class SignUpForm(UserCreationForm):

    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = CustomUser
        fields = ('id_card', 'first_name', 'last_name', 'email', 'id_card_scan', 'password1', 'password2')   #campi da salvare

    def clean_id_card_scan(self):

        id_card_scan = self.cleaned_data.get('id_card_scan')

        try:
            # Valida estensione
            ext = os.path.splitext(id_card_scan.name)[1]
            valid_extension = ['.pdf', '.jpg']
            if not ext.lower() in valid_extension:
                raise ValidationError(u'Utilizza un file PDF o JPEG')

            # Valida dimensione
            if len(id_card_scan) > (3000 * 1024):
                raise forms.ValidationError("La dimensione del file non deve essere superiore a 3MB")

        except AttributeError:

            pass

        return id_card_scan


class GroupAdminForm(forms.ModelForm):

    class Meta:
        model = Group
        exclude = []

    # Add the users field.
    users = forms.ModelMultipleChoiceField(
        queryset=CustomUser.objects.all(),
        required=False,
        # Use the pretty 'filter_horizontal widget'.
        widget=FilteredSelectMultiple('users', False),
    )

    # def __init__(self, *args, **kwargs):
    #     instance = kwargs.get('instance', None)
    #     if instance is not None:
    #         initial = kwargs.get('initial', {})
    #         initial['users'] = instance.user_set.all()
    #         kwargs['initial'] = initial
    #     super(GroupAdminForm, self).__init__(*args, **kwargs)

    def __init__(self, *args, **kwargs):
        # Do the normal form initialisation.
        super(GroupAdminForm, self).__init__(*args, **kwargs)
        # If it is an existing group (saved objects have a pk).
        if self.instance.pk:
            # Populate the users field with the current Group users.
            self.fields['users'].initial = self.instance.user_set.all()

    def save_m2m(self):
        # Add the users to the Group.
        self.instance.user_set.set(self.cleaned_data['users'])

    def save(self, *args, **kwargs):
        # Default save
        instance = super(GroupAdminForm, self).save()
        # Save many-to-many data
        self.save_m2m()
        return instance

templates/base.html
<!DOCTYPE html> {% load staticfiles %}

<html>

<head>
    <title>Survey {% block title %}{% endblock %} Page</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 ,maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="guppo puccano">
    <!-- style  and bs -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/medias.css' %}">
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan" rel="stylesheet">
    <!-- iconfont -->
    <script src="https://use.fontawesome.com/a8f6feea50.js"></script>
</head>

<body>
    <nav class="navbar navbar-fixed-top" id="my-nav">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'survey'%}">SURVEY</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav" id="menu-items">
                    <li>
                        <a href="{% url 'survey'%}"><i class="icon icon icon-mini"></i>Home</a>
                    </li>
                    <li>
                        <a href="#"><i></i>Info</a>
                    </li>
                    <li>
                        <a href="{% url 'profile'%}"><!--<i class="icon icon-man icon-mini"></i>-->Profilo</a>
                    </li>
                    <!-- @ilfonty BEGIN-->
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout'%}">Disconnettiti</a></li>
                    <li id="user"><i class="fa fa-user-circle-o"></i> Ciao {{ user.get_username }}</li>
                    {% else %}
                    <li><a href="{% url 'login'%}">Collegati</a></li>
                    {% endif %}
                    <!-- @ilfonty END-->
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>



    <!-- page content -->
    <div class="container" id="main-cont">
        <div class="row">
            <!-- il contenuto del template base è nelle pagine survey e ...--->
            {% block content %} {% endblock %}
        </div>
    </div>

    <!--footer start from here-->
    <footer>
        <div class="borderissimo"></div>
        <div class="container">
            <div class="row">
                <div class="footer-content">
                    <div class="col-md-4 col-sm-6 minidesc">
                        <h6>Survey</h6>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
                        <p><i class="fa fa-map-pin"></i> indirizzo Comune n 11</p>
                        <p><i class="fa fa-phone"></i> Telefono(IT) : +39 9999 878 398</p>
                        <p><i class="fa fa-envelope"></i> E-mail : info@survey.com</p>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <h6 class="heading7">Link Utili</h6>
                        <ul class="footer-ul">
                            <li><a href="#"> Info (FAQ)</a></li>
                            <li><a href="#"> Sito Comune</a></li>
                            <li><a href="{% url 'logout'%}"> Logout</a></li>
                            <li><a href="#"> Site map</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <h6 class="heading7">Ultimi Sondaggi</h6>
                        <div class="post">
                            <p>Sondaggio Strade<span>Ottobre 16, 2017</span></p>
                            <p>Sondaggio Servizio Idrico<span>Ottobre 16, 2017</span></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
        <div class="container">
            <div class="col-md-12">
                <p>©Survey 2017 - All Rights reserved</p>
            </div>
        </div>
    </div>
    </footer>
    <!--footer ends here -->

    <!-- Bootstrap core JavaScript
        ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <!--<script href="{% static 'js/survey.js' %}"></script>-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
     <script type="text/javascript">
        function unlock(cekb, btn) {
            if(cekb.checked) {
                document.getElementById(btn).disabled = false;
            } else {
                document.getElementById(btn).disabled = 'disabled';
            }
	}
    </script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
    <h1>Gruppo Puccano</h1>

        <p>Welcome to <em>Survey</em>, a very stressful Django website, developed by 4 lazy programmers.</p>

    <h2>Contenuti</h2>

      <ul>
        <li><strong><a href="{% url 'survey' %}">Surveys:</a> </strong> {{ num_surveys }}</li>
      </ul>

{% endblock %}

templates/question.html
{% extends 'base.html' %}
{% block title %}Questionario{% endblock %}

{% block content %}
<div class="question">
	<form action="{% url 'vote' question.id %}" method = "post">
    <div class="question-container">
        <h2>{{ question.question_text }}</h2>
		{% csrf_token %}
        <ul>
          <li>
            <input type="radio" id="f-option" name="answer" value="1" onclick="unlock(this, 'vote-btn')">
              <label for="f-option">{{ question.answer_1 }}</label>
            <div class="check"></div>
          </li>

          <li>
            <input type="radio" id="s-option" name="answer" value="2" onclick="unlock(this, 'vote-btn')">
              <label for="s-option">{{ question.answer_2 }}</label>
            <div class="check"></div>
          </li>
          <li>
            <input type="radio" id="t-option" name="answer" value="3" onclick="unlock(this, 'vote-btn')">
              <label for="t-option">{{ question.answer_3 }}</label>
            <div class="check"></div>
          </li>
        </ul>
		<input class="radiobtn" type="hidden" name="survey" value="{{ survey.id }}">
		{% if nextquestion %}
			{% if newtopic %}
				<input type="hidden" name="topic" value="{{ newtopic.id }}">
			{% else %}
				<input type="hidden" name="topic" value="{{ topic.id }}">
			{% endif %}
			<input type="hidden" name="nextquestion" value="{{ nextquestion.id }}">
		{% else %}
			<input type="hidden" name="nextquestion" value="0">
		{% endif %}
    </div>
    <input id="vote-btn" type="submit" value="Vote" disabled="disabled"/>
	</form>
</div>
{% endblock %}

templates/report.html
{% extends 'base.html' %}
{% block title %}Report-Questionario{% endblock %}

{% block content %}
<h2> REPORT </h2>
{% for element in data %}
	<div class="col-md-12 question-report">
		<h3>{{ element.question.question_text }}</h3>
		<p><span>{{ element.question.answer_1 }} - {{ element.percentage_1 }}%</span> - ({{ element.question.votes_1 }}/{{ element.total_votes }})</p>
		<p><span>{{ element.question.answer_2 }} - {{ element.percentage_2 }}%</span> - ({{ element.question.votes_2 }}/{{ element.total_votes }})</p>
		<p><span>{{ element.question.answer_3 }} - {{ element.percentage_3 }}%</span> - ({{ element.question.votes_3 }}/{{ element.total_votes }})</p>
	</div>
{% endfor %}
{% endblock %}

templates/survey.html
{% extends 'base.html' %} {% block content %}

<h1 class="survey-page">Sondaggi Disponibili</h1>
<!-- ciclo for ??? -->

    {% if not surveys %}
            <div class="col-md-12" id="completed" >
                <i class="fa fa-trophy"></i>
                <h2> Congratulazioni! tutti i sondaggi sono completati</h2>
            </div>
        {% endif %}
{% for survey in surveys %}

<div class="col-md-12 survey-card">
    <div class="main-info">
        <h2>{{ survey.survey_title }}</h2>
        <p>{{ survey.survey_description }}</p>
    </div>
    <hr>
    <div class="info-container">
        <p><span>Domande</span> : {{ survey.num_questions }} </p>
        <p><span>Tempo</span> : 2 minuti </p>
    </div>
    <div class="btn-container">
        <a href="{% url 'question' survey.id survey.topic_set.first.id survey.topic_set.first.question_set.first.id %}">
            <button><i class="fa fa-check fa-2x"></i><p>Esegui</p></button>
        </a>
        <!-- manca la funzione elimina sondaggio per chi non vuole eseguirlo -->
        <button><i class="fa fa-times fa-2x"></i><p>Salta</p></button>
    </div>
</div>
<hr> {% endfor %} {% endblock %}

templates/survey_questions.html
{% extends 'base.html' %}
{% block title %}Questionario{% endblock %}

{% block content %}

<h1 class="questions-page">Domande</h1>

    <h1> {{ x }}</h1>

<!-- ciclo for ??? qui c'è il problema -->
    <div class="col-md-12 questions-lis">
        {% for question in questions.all %}
        <div class="question">
            <h3>{{ question.question_text }}</h3>
            <p>{{ question.answer_1 }}</p>
            <p>{{ question.answer_2 }}</p>
            <p>{{ question.answer_3 }}</p>
        </div>
        <hr>
        {% endfor %}
        <div class="btn-submit-questions">
            <button><i class="icon icon-accept"></i><p>Invia</p></button>
            <button><i class="icon icon-close"></i><p>Annulla</p></button>
        </div>
    </div>
    <hr>-->

{% endblock %}